//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingWebAPIProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]public partial class OrderDetail
    {
        [DataMember]public int OrderId { get; set; }
        [DataMember]public int ProductId { get; set; }
        [DataMember]public Nullable<int> Quantity { get; set; }
        [DataMember]public Nullable<decimal> Price { get; set; }
    
        [DataMember]public virtual Order Order { get; set; }
        [DataMember]public virtual Product Product { get; set; }
    }
}
