//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingWebAPIProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]public partial class Retailer
    {
        [DataMember]public int RetailerId { get; set; }
        [DataMember]public Nullable<decimal> RetailerRevenue { get; set; }

        [IgnoreDataMember] public virtual User User { get; set; }
    }
}
